name: logitrust_drivers
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  


  firebase_core: ^3.2.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.2
  firebase_database: ^11.0.3
  fluttertoast: ^8.2.6
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  flutter_polyline_points: ^2.1.0
  location: ^7.0.0
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  cloud_firestore: ^5.1.0
  elegant_notification: ^2.2.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1

  
  dio: ^5.5.0+1
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    
